- doc.go
The function argument to ebiten.Run takes an *ebiten.Image,
and must return an error.
> Update example in doc.go

- index.html
The "Getting Started" section walks a dev through creating a little
"Hello world!" program with Ebiten to give them a sense of what a
barebones Ebiten game could look like.
I find "Hello world!" to be a nice starting point to get a sense of what
it looks like to use a library, and it gets people started pretty
quickly.
Closes #233.
-----
@hajimehoshi let me know if this is something you find useful. I
would be happy to write a tutorial for the docs on building a more fully
featured simple game too.
> doc: Add Getting Started section

- examples/physics/main.go
A simple non-interactive physics demo using fork of Chipmunk2D.
> examples: Add physics example

- audio/mp3/decode_js.go
- audio/mp3/float32_wasm.go
- ebitenutil/file_js.go
- examples/contextlost/main.go
- internal/clock/now_js.go
- internal/devicescale/impl_js.go
- internal/input/input_js.go
- internal/opengl/context_js.go
- internal/ui/ui_js.go
- internal/web/js.go
I plan to merge this right after
https://github.com/gopherjs/gopherwasm/pull/3 is merged.
> Use new GopherWasm API

- image.go
- internal/affine/colorm.go
- internal/graphics/command.go
- internal/graphics/image.go
- internal/graphics/program.go
- internal/graphics/shader.go
- internal/graphicsutil/vertices.go
- internal/restorable/image.go
- internal/restorable/images_test.go
- internal/shareable/shareable.go
- internal/shareable/shareable_test.go
> Embed color matrices values to vertices

- ebitenutil/file_js.go
* Change to use `js.NewCallback`
* Use `uint8contentWrapper := js.Global().Get("Uint8Array").New(content)`, without this all the bytes in `data` stays zeroed. (TypedArray cannot use `set` on an ArrayBuffer)
> ebitenutil/file: Fix OpenFile() so it works with wasm

- .travis.yml
> Retrieve correct commits in PRs

- input.go
- internal/driver/input.go
- internal/glfw/glfw_notwindows.go
- internal/glfw/glfw_windows.go
- internal/uidriver/glfw/input.go
- internal/uidriver/js/input.go
- internal/uidriver/mobile/input.go
Here's my first attempt at #1034.
I'm not sure if I can make the string returning functions more robust or not, might be an issue constantly allocating these?
> gamepad: add GamepadGUID and GamepadName functions

- ebitenutil/loadimage.go
Added js to build tags as suggested by @hajimehoshi
> Fix missing js build tag

- inpututil/inpututil.go
Durations for key presses and gamepad button presses were being stored
in map[int]int, where the key values were always small integers, and
furthermore, were always contiguous and contained the whole set. It's
much faster and cheaper to do those with slices.
We could probably do this with mouse buttons, but I was wary of that
code because I don't see any handling for more-than-three-button
mice. Similar logic could perhaps apply to touch events, but there
it might make more sense to use a dynamic allocation of some kind.
It might be more efficient to just swap the two slices back and
forth, computing the new values from the previous values and
then swapping the slice arrays themselves, but that seemed like
a more intrusive change.
> use slices for maps where keys are small contiguous integers

- examples/wheel/main.go
> examples/wheel: Use RunGame

- internal/graphicsdriver/opengl/context_desktop.go
- internal/graphicsdriver/opengl/context_notx.go
- internal/graphicsdriver/opengl/context_x.go
- internal/graphicsdriver/opengl/gl/package_x.go
> graphicsdriver/opengl: Forbids PBO on Raspberry Pi 4

- examples/contextlost/main.go
- examples/windowsize/main.go
- run.go
- uicontext.go
> Rename ScreenClearing functions

- input.go
> Add inpututil guide comment for Is{Key,MouseButton,Gamepad}Pressed and TouchIDs

- CONTRIBUTING.md
- doc.go
The use of panic is to match the image.
> Fix typos, and use panic instead of log.Fatal in doc.go

- README.md
I checked the other sections of README and that part looked kinda inconsistent, thus made this minor change. I think it will make more convenient to look at the license for those who are interested in.
> created hyperlink to LICENSE file in README.md

- examples/touch/main.go
I was looking for an example on how to use the Touch APIs in ebiten to implement complex touch gestures, but was unable to find any. This PR adds the examples I was looking for.
https://gophers.slack.com/archives/C19491JS2/p1615525929193900
> Add a new Touch example

- .github/workflows/test.yml
> Reenable the Wasm test on Ubuntu

- .github/workflows/test.yml
> Add Android build on GitHub Actions

- .github/workflows/test.yml
> Add iOS build on GitHub Actions

- internal/uidriver/js/ui_js.go
- run.go
> Issue 1611

- cursor.go
- examples/cursor/main.go
- internal/driver/cursor.go
- internal/uidriver/glfw/ui.go
- internal/uidriver/glfw/ui_darwin.go
- internal/uidriver/glfw/ui_unix.go
- internal/uidriver/glfw/ui_windows.go
- internal/uidriver/js/ui_js.go
- Adds CursorShapeHorizontalResize & CursorShapeVerticalResize.
**Need someone to test on Windows and Linux.**
re: #1571
> ui: Native macOS implementation for setting cursor shape

- examples/stars/main.go
Add a new example that looks like space travel.
This demonstrates usage of ebitenutil.DrawLine and looks fun.
You can see a live demo with your browser [here](https://kumagi.github.io/ddef/)
> add an example "stars"

- image.go
- image_test.go
> Add (*Image).RGBA64At

- examples/vibrate/main.go
- internal/driver/ui.go
- internal/uidriver/glfw/ui.go
- internal/uidriver/js/ui_js.go
- internal/uidriver/mobile/vibrate_android.go
- internal/uidriver/mobile/vibrate_ios.go
- vibrate.go
> ebiten: Add VibrationOptions to specify intensity

- internal/graphicscommand/command.go
- internal/graphicscommand/thread.go
- internal/thread/thread.go
- internal/uidriver/glfw/run_notsinglethread.go
- internal/uidriver/glfw/ui.go
- internal/uidriver/glfw/window.go
- internal/uidriver/mobile/ui.go
- run.go
> ebiten: add RunOnMainThread(func())

- internal/glfw/glfw_notwindows.go
- internal/glfw/glfw_windows.go
- internal/ui/ui_glfw.go
- internal/ui/window_glfw.go
- internal/ui/window_null.go
- window.go
This PR adds a new method that fixes the aspect ratio while resizing.
#1804
> Add SetWindowKeepAspectRatio

- image_test.go
Before https://github.com/hajimehoshi/ebiten/pull/1996, this failed with:
image_test.go:1997: At(1, 0): got: {64 64 128 255}, want: {0 128 128 255}
The difference is:
- Before, colors were interpolated in straight-color space:
- Background: {0 0 255 255}
- Vertex A: {255 0 0 0}
- Vertex B: {0 255 0 255}
- Interpolated: {128 128 0 128}
- Premultiplied: {64 64 0 128}
- Onto Background: {64 64 128 255}
- After, colors are interpolated in premultiplied space:
- Background: {0 0 255 255}
- Vertex A: {255 0 0 0}
- Vertex A premultiplied: {0 0 0 0}
- Vertex B: {0 255 0 255}
- Vertex B premultiplied: {0 255 0 255}
- Interpolated: {0 128 0 128}
- Onto Background: {0 128 128 255}
This DIFFERS from the sample fragment shader, which returns the color as is
(Kage allows vertex color values to be used …
> Pre-failing test for color interpolation during rendering.

- audio/audio.go
- audio/player.go
> audio: add (*Player).UnplayedBufferSize

- ebitenutil/shapes.go
> Issue 2163 add circle

- internal/graphicsdriver/directx/graphics_windows.go
> internal/graphicsdriver/directx: batch ResourceBarrier commands

- graphics.go
- internal/ui/context.go
- internal/ui/graphics.go
- internal/ui/ui.go
- internal/ui/ui_android.go
- internal/ui/ui_cbackend.go
- internal/ui/ui_glfw_darwin.go
- internal/ui/ui_glfw_unix.go
- internal/ui/ui_glfw_windows.go
- internal/ui/ui_ios.go
- internal/ui/ui_js.go
> added api for getting debug info (only graphics libray so far)

- ebitenutil/fs_go116.go
> ebitenutil: add NewImageFromFileSystem()

- examples/gamepad/main.go
- input.go
- internal/gamepad/gamepad.go
- internal/gamepad/gamepad_android.go
- internal/gamepad/gamepad_cbackend.go
- internal/gamepad/gamepad_darwin.go
- internal/gamepad/gamepad_desktop_windows.go
- internal/gamepad/gamepad_ios.go
- internal/gamepad/gamepad_js.go
- internal/gamepad/gamepad_linux.go
- internal/gamepad/gamepad_null.go
- internal/gamepad/gamepad_xbox_windows.go
- internal/gamepaddb/gamepaddb.go
> ebiten: add IsStandardGamepadAxisAvailable and IsStandardGamepadButtonAvailable

- examples/fullscreen/main.go
- examples/keyboard/keyboard/gen.go
- examples/spriteshd/main.go
- examples/windowclosing/main.go
- internal/buffered/image_test.go
- internal/processtest/testdata/issue1753.go
- internal/processtest/testdata/issue2079.go
- internal/processtest/testdata/issue2089.go
- internal/processtest/testdata/issue2129.go
- internal/processtest/testdata/issue2138.go
- internal/processtest/testdata/issue2154_1.go
- internal/processtest/testdata/issue2154_2.go
- internal/processtest/testdata/issue2162.go
- internal/processtest/testdata/issue2180.go
- internal/testing/testing.go
- run.go
- add RegularTermination, fix RunGame, correct references to Run
- ensure tests pass
- example tests also pass
- closes #2266
- second attempt at #2271, don't you love git
> regular termination (again)

- internal/ui/ui_glfw.go
- internal/ui/window_glfw.go
> ebiten: allow maximizeWindow when no max boundaries are set

- inpututil/inpututil.go
* append just pressed and just released methods for keys
* append all, just pressed and just released methods for gamepads
* fixes #2381
Note: I could also add methods for standard gamepad buttons if desired
> inpututil: new APIs for keys and gamepads

- .github/workflows/vettools/imageimportcheck.go
- examples/drag/main.go
- examples/keyboard/keyboard/gen.go
- examples/shader/main.go
- genevents.go
- image.go
- internal/debug/debug_ebitenginedebug.go
- internal/debug/debug_notebitenginedebug.go
- internal/gamepad/gamepad.go
- internal/glfwwin/api_windows.go
- internal/graphicscommand/image_js.go
- internal/graphicsdriver/metal/mtl/example_darwin_test.go
- internal/graphicsdriver/opengl/gl/conversions.go
- internal/processtest/testdata/issue1753.go
- internal/ui/shader.go
- internal/ui/ui_js.go
- shader.go
- shader_test.go
Closes #2429 
Refactoring
Replaces all `interface{}` to `any`, just because :)
Adds `.idea` into `.gitignore`
> all: replace `interface{}` with `any`

- .gitignore
None
Developer convenience
Adds `.idea` folder in `.gitignore` as this folder is always generated when using JetBrains IDEs
> Added `.idea` in `.gitignore`

- text/text.go
Before this change, CacheGlyphs created only necessary glyphs wihtout considering variations by sub-pixels in X direction. This was sometimes unexpected when a user might want to prepare glyph cache with a string including all the letters, instead of actual texts.
This change makes CacheGlyphs create all the sub-pixel variations of the given runes.
Updates #2469
Updates #2528
> text: make CacheGlyphs create all the sub-pixel variations

- text/text.go
- text/text_test.go
Signed-off-by: Pierre Curto <pierre.curto@gmail.com>
None.
Typos.
Minor typos, making sure fields are set when initializing structs and removing unused function parameters.
> text: fix typos and add fields to struct initializers

- examples/camera/main.go
s/Tiles/Camera/
This example was probably a "tiles" example before and we got the same title after copying the code.
Minor issue in the example.
Fixes a typo in the example.
> examples/camera: fix window title

- examples/capture/main.go
#2641
feature
Provides an example of mouse capture, using similar style as the mouse wheel example.
> mouse capture example

- internal/graphicscommand/command.go
- internal/shader/expr.go
- internal/shader/shader.go
- internal/shader/stmt.go
- internal/shader/type.go
delete unnecessary use of fmt.Sprintf
> chore: unnecessary use of fmt.Sprintf

- examples/lines/main.go
n/a
n/a
Removes duplicated code from one of the samples.
The next two lines are the same as the ones being removed.
> Remove duplicated code

- go.mod
- go.sum
- internal/ui/ui_glfw_darwin.go
updates #1162 
Use the new ObjC API inside of purego.
> internal/ui: Use new OBJC API

- image.go
- internal/atlas/image.go
- internal/atlas/image_test.go
- internal/atlas/shader_test.go
- internal/buffered/image.go
- internal/graphicscommand/command.go
- internal/graphicscommand/image.go
- internal/graphicscommand/image_test.go
- internal/graphicsdriver/directx/graphics11_windows.go
- internal/graphicsdriver/directx/pipeline12_windows.go
- internal/graphicsdriver/graphics.go
- internal/graphicsdriver/metal/graphics_darwin.go
- internal/graphicsdriver/opengl/graphics.go
- internal/mipmap/mipmap.go
- internal/restorable/image.go
- internal/restorable/images_test.go
- internal/restorable/shader_test.go
- internal/ui/image.go
> internal/graphicsdriver: replace Region with image.Rectangle

- .github/workflows/vuln.yml
Closes #2573
refactor
Swap from hard coded versions of go to dynamically acquiring the latest stable versions from https://go.dev/dl/?mode=json
> Dynamic Go versions in vuln workflow

- examples/drag/main.go
Typo in drag and drop example
Typo
Remove duplicated code
> Remove duplicated line in drag and drop example

- vector/path.go
> Typo (segument -> segment)

- examples/platformer/main.go
> More descrpitive platformer comments

- internal/atlas/image.go
- internal/packing/packing.go
Closes #2914
performance
Rewrite the power of 2-like functions with bit manipulation.
> Use bit manipulation for function power of 2 -like functions

- internal/glfw/window_unix.go
- text/v2/gotext.go
> chore: fix function names in comment

- ebitenutil/file_js.go
> fix: close res body

- examples/windowsize/main.go
> examples/windowsize: update main.go

- geom.go
missing rotation info
missing rotation info
> ebiten: update GeoM.Rotate() comment

- examples/airship/main.go
- examples/alphablending/main.go
- geom_test.go
- image_test.go
None
Modernizes for loops
Modernizes for loops in the codebase
> modernize for loop

- examples/2048/2048/board.go
None
removing unused code
removing unused code in 2048/2048
> remove unused tileAt func in 2048/2048/board

- cmd/ebitenmobile/main.go
Partially addresses https://github.com/hajimehoshi/ebiten/issues/2436 by removing dead code. 
Code clean up.
Deletes unused `goEnv` function.
> ebitenmobile delete unused goEnv func

- examples/doomfire/main.go
Replaced for-loops in updateFirePixels with range-based loops for clarity. Simplified newI calculation in updateFireIntensityPerPixel using max().
> Refactor fire pixel update loops and intensity logic

- colorm/colorm.go
documentation for colorm
Adds some extra information to the colorm documentation about how colorm operates.
> extra notes on how colorm operates
