- internal/graphics/opengl/context_js.go
Run calls Check whether or not gopherjs is used, and it was not implemented here.
> Check was missing from context_js

- internal/ui/hide_console_dummy.go
- internal/ui/hide_console_notwindows.go
- internal/ui/hide_console_windows.go
- internal/ui/ui_glfw.go
When compiling on Windows without the -ldflags "-Hwindowsgui" flag, a
console window pops up when running a compiled program.
This change hides the console after the program starts. The console is
visible for a moment before the actual game window shows.
> Hide console window on Windows

- internal/ui/ui_glfw.go
I have implemented it just for desktop to detect the pulse input less than 1/60 minute. I don't know much about for browser or mobile.
It should resolve https://github.com/hajimehoshi/ebiten/issues/314 and https://github.com/hajimehoshi/ebiten/issues/399 for desktop.
> glfw: Add StickyModes to window.InputMode (resolve #314 #399)

- input.go
Touches() will always allocate a new slice to copy touches into even if no touches are reported, for example on desktop. Adding a simple check makes sure that this unnecessary allocation does not happen.
> Do not allocate a touch slice if no touches have been made

- input.go
- internal/input/input_glfw.go
- internal/input/input_js.go
- internal/input/input_mobile.go
- internal/ui/ui_glfw.go
- internal/ui/ui_js.go
This change simply adds the funcionality to read mouse wheel input, which (at least for me) is a very necessary feature. My solution is clearly not perfect, as I do rely on somewhat of a workaround to reset the scrolling value to 0 while no scroll events happen. That should probably be changed, but I hope  you forgive me for that, as I am absolutely new to go and haven't been able to find an alternative to this yet, though it's probably pretty easy.
> Enable mouse wheel input

- ebitenutil/debugprint.go
Add the DebugPrintAt to print some debug informations where you want on the screen.
Usage : DebugPrintAt (surface, text, x_coord, y_coord)
> Add the DebugPrintAt function and close Issue #683

- image.go
- internal/graphics/vertices.go
- internal/shareable/shareable.go
DrawTriangles is expensive and slow because of massive memory
allocation and garbage collection costs. This patch moves from ~47TPS
on my laptop (with ~24k triangles) to 60TPS. The first part
is just allocating the right size of vertex buffer up front; that
got to about 55TPS. The second part replaces the frequent
allocations of []float32 in Vertex() calls with writing the
desired values into a provided destination slice.
Time spent in drawing triangles for 1,000 frames:
13.07s	baseline
11.09s	preallocate whole buffer to avoid resizing
6.13s	use new PutVertex function
This might need some cleanup, but I think it's good evidence that
the design change is viable.
> Speed up DrawTriangles

- internal/devicescale/impl_unix.go
- internal/ui/ui_glfw.go
- internal/ui/ui_unix.go
resolves https://github.com/hajimehoshi/ebiten/issues/729
In Linux (and at least when using Gnome) requesting the monitors and scaling factor is very time consuming.
We can cache the list of all monitors and simply subscribe to a window change event to recalculate the window cache. This will get rid of needing to re-calculate monitors on every call to 'currentMonitorImpl' (at least in unix). The cache is implemented for all desktop clients because it could be helpful to other OSes (not just unix)
Additionally the scale can be cached for at least a single frame. It is possible that different monitors have different scale factor so the cache will probably need to be upgraded to be per-monitor once that is supported in unix.
I am not sure how to tell when a frame begins and ends (might be …
> Added monitor cache and scale cache

- internal/graphicsdriver/metal/driver.go
I was getting the following error on High Sierra
```
program_source:141:7: error: call to 'clamp' is ambiguous
```
This change fixes the compile error
> Clarify the type of passing parameters

- internal/graphicscommand/driver_mac.go
Those early MacOS devices such like `iMac (21.5-inch, Mid 2011)`  do not support Metal.  
"Metal is not supported on this system"
I added a patch to detect whether this Mac support Metal , and use Opengl instead if not.
> use Opengl instead on early MacOSX platform which does not support Metal

- image.go
This change uses a pattern that Go 1.11+ compilers can optimize to a clear operation
https://github.com/golang/go/blob/master/doc/go1.11.html#L447
**Why do this?**
Seems like an idiotmatic change and reduces amount of allocations used by Ebiten. I didn't see any performance improvement but it gave me one less thing to think about when profiling allocations.
> image: clear mipmap map to avoid unnecessary allocation

- ebitenutil/loadimage.go
go-bindata is not appropriate because no longer maintained.
Now I suggest rakyll/statik insteadly which is actively maintained.
NOTE: I confirmed that go-bindata is documented only here.
> Change docs about go-bindata into rakyll/statik

- audio/vorbis/vorbis.go
- internal/graphicsdriver/opengl/program.go
- internal/restorable/images_test.go
- internal/shareable/shareable.go
- internal/testflock/flock_notjs.go
- Removed unused variables and constants
- Removed a redundant return statement
- Updated flock.NewFlock to flock.New (NewFlock is deprecated)
> Small cleanup

- .travis.yml
This should fix the errors opening /etc/init.d/xvfb
> Add xvfb service to .travis.yml explicitly

- cursormodes.go
- internal/driver/cursormode.go
- internal/driver/ui.go
- internal/glfw/const.go
- internal/uidriver/glfw/ui.go
- internal/uidriver/js/ui.go
- internal/uidriver/mobile/ui.go
- run.go
Closes #1014 
The API is separate from the cursor visibility function for backwards compatibility. Combining the APIs into one function (SetCursorMode, or something similar) may be more elegant.
> Add cursor capture functionality

- internal/packing/packing.go
- internal/uidriver/glfw/ui.go
Fixes a typo in a comment and a typo in a panic message found via https://goreportcard.com/
> Typo Corrections from https://goreportcard.com/

- examples/life/main.go
Because golang executes the init function after establishing
the variables in the var block, the random number seed wasn't
initializing until after the initial world state had gotten
established (leading to an identical game of Life on every run).
To fix this, we establish an empty world in the var block,
and then populate it in the init function after the random
number generator has been seeded.
> Fix initial world randomization

- internal/uidriver/mobile/ui.go
Current implementation of `setGBuildSizeCh` causes `panic: close of closed channel`.
Introduced `sync.Once` to avoid this.
> Fix multiple close for channel

- internal/buffered/image.go
`resolvePendingPixels` must be called in `delayedCommands`.
Otherwise, following `init` function does not work:
```go
func init() {
srcImg, _ := ebiten.NewImage(w, h, ebiten.FilterDefault)
dstImg, _ := ebiten.NewImage(w, h, ebiten.FilterDefault)
// Set some pixels
srcImg.Set(16, 16, clr)
// Previous Set() is ignored, and nothing is drawn on dstImg.
dstImg.DrawImage(srcImg, nil)
}
```
> Fix delayed DrawImage()

- input.go
- internal/driver/input.go
- internal/uidriver/glfw/input.go
- internal/uidriver/js/input.go
- internal/uidriver/mobile/input.go
Gamepad GUID is a SDL specific notion and, strictly speaking,
they are not GUID (UUID) since they don't follow UUID's
specifications.
Renaming the function makes the situation clearer.
Updates #1048
> input: Rename GamepadGUID -> GamepadSDLID

- image.go
- internal/buffered/command.go
- internal/buffered/image.go
- internal/graphicscommand/command.go
- internal/graphicscommand/image.go
- internal/graphicscommand/image_test.go
- internal/mipmap/mipmap.go
- internal/restorable/image.go
- internal/restorable/images.go
- internal/restorable/images_test.go
- internal/shareable/export_test.go
- internal/shareable/image.go
- internal/shareable/image_test.go
- uicontext.go
Now grpahicscommand saves the error and shows the error after a
while. This was good to simplify the API but was the cause to hide
some issues.
This change fixes all the errors to be returned immediately, and
buffer this in the ebiten package instead.
Fixes #971
> graphicscommand: Return the error immediately

- examples/raycasting/main.go
The x and y axis have been confused. If screenWidth and screenHeight are not equal the game will fail on collision with the bottom.
> fix bug in raycast example, swap height and width

- internal/buffered/image.go
- internal/mipmap/mipmap.go
This simple change brings my simple test project from 752 allocations per frame to 474 allocations per frame. It seems a shame that go's escape analysis is not smart enough to leave this variable on the stack.
GeoM is a 24-byte struct and there is a slight perf difference that we are storing it in stack, but also copying it around with this change (instead of an 8-byte pointer). This could make things faster (due to stack / CPU cache) or slower (due to copying more memory) - when I try a stress test (drawing 100K images per frame), I can't see any actual performance difference (but I do see 100K fewer allocations, and GC is no longer running almost all the time).
> Fix more unnecessary allocations per frame

- doc.go
- examples/moire/main.go
- examples/windowsize/main.go
- imagedumper_desktop.go
- imagedumper_notdesktop.go
- run.go
- uicontext.go
This change adds an optional function Draw to the Game interface.
With Draw function, the game logic and rendering are separate.
There are some benefits:
* The API is clearer and easier to understand.
* When TPS < FPS, smoother rendering can be performed without
changing the game logic depending on TPS.
* Porting to XNA, which has separate functions Update and Draw,
would be a little easier.
Draw is optional due to backward compatibility. Game interface was
already used before v1.11.x in mobile packages, and adding a
function would break existing code unfortunately. Then, we adopted
switching the behavior based on whether Draw is implemented or not
by type assertions.
IsDrawingSkipped will always return true when Draw is implemented.
Fixes #1104
> ui: Add an optional function Draw function to Game interface

- examples/raycasting/main.go
The `points()` function in the raycasting example duplicated the last point on closed objects. I added an if condition to avoid this.
In addition, I found it useful to debug print the number of rays used
> [raycasting example] Fixed duplicated points, plotting ray count

- examples/audiopanning/main.go
This example simulates an audio source (sprite) and an audio listener (camera). The panning is relative to the sprite's position.
Closes #1224 
Edit: The example should be run with stereo speakers or headsets 😅
Example:
https://cquiz-us.s3.amazonaws.com/gtest/index.html
> Stereo audio panning example

- graphics.go
- internal/driver/compositemode.go
- internal/graphicsdriver/opengl/context.go
- internal/graphicsdriver/opengl/context_desktop.go
- internal/graphicsdriver/opengl/context_js.go
- internal/graphicsdriver/opengl/context_mobile.go
- internal/graphicsdriver/opengl/gl/package.go
This pull request adds a new composite mode called `CompositeModeMultiply`, which multiplies the source color with the destination color.
I have tested my changes on Linux and Windows only.
Closes #410
> Add CompositeModeMultiply

- .builds/alpine.yml
- .builds/arch.yml
- .builds/debian.yml
- .builds/fedora.yml
- .builds/ubuntu.yml
This pull request adds various build manifests that will be used by sourcehut builds. It tests the installation of Ebiten on the following distros:
- Alpine Linux
- Arch Linux
- Debian
- Fedora
- Ubuntu
If you configure sourcehut dispatch with this repository, they will be run after every commit.
> Add various build manifests

- image.go
"The default (zero) value is identify" -> "The default (zero) value is identity"
> Fix typo in the documentation for DrawImageOptions

- image.go
- internal/graphicsdriver/opengl/gl/package_notwindows.go
- internal/graphicsdriver/opengl/gl/package_windows.go
- run.go
Fix the issue with comment heading in `pkgsite`: https://github.com/golang/go/issues/41616
I wrote a simple [Go program](https://gist.github.com/trongbq/424bbc6a4cc79a20d17233d4fa1b1b5b) to detect these kind of comments. It showed following output:
```
1)File: cursormode.go:23
Comment: // Cursor Modes
2)File: examples/keyboard/keyboard/gen.go:262
Comment: // You may obtain a copy of the License at
3)File: gamepad.go:24
Comment: // GamepadButtons
4)File: genevents.go:309
Comment: // You may obtain a copy of the License at
5)File: genkeys.go:635
Comment: // You may obtain a copy of the License at
6)File: image.go:402
Comment: // DrawTrianglesShaderOptions represents options for DrawTrianglesShader
7)File: image.go:534
Comment: // DrawRectShaderOptions represents options for DrawRectShader …
```
> Fix the comment style cause heading in pkgsite

- internal/restorable/image.go
- internal/restorable/images.go
- internal/shareable/image.go
When context losts never happen, reading pixels and call replace-pixels command are not needed.
Closes #1508
> internal/shareable: Call DrawTriangles instead of ReplacePixels at makeShared

- internal/graphicscommand/command.go
Using `-tags=ebitendebug` would log the string: 
```
%!s(PANIC=String method: graphicscommand: invalid composite mode: 13)
```
When using the multiply composite mode. This adds it to the string function.
> internal/graphicscommand: fix missing composite mode

- internal/devicescale/impl_windows.go
This fixes a crash on at least one of my customer's machines. I don't have access to the machine, so I don't know why it's failing.
Instead of crashing, just falls back to other DPI.
> Fallback to simpler logic when trying to get DPI from monitor and failing

- internal/uidriver/glfw/run_notsinglethread.go
In `internal/uidriver/glfw/run_notsinglethread.go`, if the `UserInterface.init()` function returns an error, the `loop` is executed regardless and the error is discarded. This behavior will hide the error returned by `init()` and might trigger some crashes (see #1688 ).
A partial fix was implemented in 6c4edf8605ea83a8c582cd228f230d1dbda213ce , however that commit alone is not enough: the code now is correctly returning the error via the `ch` channel, but it still executes the `loop()` function. This merge request skips `loop()` call if `init()` had an error.
> internal/uidriver/glfw: Bug fix: do not execute loop function if init failed

- text/text.go
drawGlyph can panic when provided with a nil *ebiten.DrawImageOptions
reference. Check that the pointer is not nil before dereferencing.
> text: Fix nil pointer dereference in drawGlyph

- input.go
- internal/driver/input.go
- internal/uidriver/glfw/input.go
- internal/uidriver/js/input_js.go
- internal/uidriver/mobile/input.go
This is only supported on desktops yet (on mobile standard layout isn't
implemented yet, and on the web this is the browser's responsibility).
Fixes #1723.
> Support updating the gamepad mapping.

- internal/devicescale/devicescale.go
- internal/devicescale/impl_android.go
- internal/devicescale/impl_desktop.go
- internal/devicescale/impl_ios.go
- internal/devicescale/impl_js.go
- internal/devicescale/impl_notx.go
- internal/devicescale/impl_x.go
- internal/uidriver/glfw/input.go
- internal/uidriver/glfw/ui.go
- internal/uidriver/glfw/ui_darwin.go
- internal/uidriver/glfw/ui_unix.go
- internal/uidriver/glfw/ui_windows.go
Fully fixes wrong dpi handling on X11 (#1774).
We now have two scale factors:
- Device scale: what GLFW calls content scale; maps window system device dependent pixels (as used for window sizes, mouse positions, frame buffers etc.) to device independent pixels (96dpi standard size).
- Screen scale: maps GLFW screen resolutions to window system device dependent pixels. Only actually is different from one on X11.
This also allows for unifying the OS dependent GLFW pixel scale conversion functions into OS independent ones in a single place.
TEST FOCUSES (will do my own round of it as well using a "weird" setup where both scales and their product aren't one):
- OS X - I am unsure about the new implementation there given the old one was very different and had a screen scale of 1. I strongly …
> Split the concept of device scale and screen scale

- audio/audio_test.go
- audio/internal/convert/float32_test.go
- audio/internal/convert/resampling_test.go
- audio/loop_test.go
- audio/vorbis/vorbis_test.go
- colorm_test.go
- examples/2048/2048/tile_test.go
- geom_test.go
- image_test.go
- imagetobytes_test.go
- internal/affine/colorm_test.go
- internal/atlas/image_test.go
- internal/atlas/shader_test.go
- internal/graphics/math_test.go
- internal/graphicscommand/image_test.go
- internal/packing/packing_test.go
- internal/restorable/images_test.go
- internal/restorable/shader_test.go
- internal/shader/shader_test.go
- internal/shaderir/ir_test.go
- shader_test.go
- text/text_test.go
Hi,
this PR removes the dot imports in test files as requested in issue #1824 
The only doubt is on the test for "2048 example" ([examples/2048/2048/tile_test.go#L18](https://github.com/hajimehoshi/ebiten/compare/main...r3vit:issue-1824-remove-dot-imports?expand=1#diff-3cd9d2a29ef6bc382e958f91e4c3b1a067740aad0d61d756706a2d173b4a99c8R18)) where I named it "example2048".
Let me know if this is what you're expecting or there is something incorrect :) 
Thank you!
> Issue 1824 - Remove dot imports from tests - Remove dot imports

- examples/audioinfiniteloop/main.go
I did not understand what "4" meant in the example, so I decided to improve the readability of it.
> Use const to represent bytePerSample

- CONTRIBUTING.md
Adds a small link to the docs readme to ensure users find the proper procedure for making a docs PR.
Signed-off-by: Jacob Salmela <me@jacobsalmela.com>
> direct users to the readme in the docs repo

- geom.go
This change fixes a misspelling of the word "multiplying" in the docstring for `ebiten.GeoM.Concat`.
> Fixes a typo.

- internal/uidriver/glfw/hideconsole_windows.go
Issue: https://github.com/hajimehoshi/ebiten/issues/485
Using `FreeConsole` (https://docs.microsoft.com/en-us/windows/console/freeconsole) instead of hiding the console correctly works on my machine.
Calling it in every case, doesn't necessarily kill the console, but prevent logs from working, so it still needs to be done when we detect that current process created its own console.
From what is stated on `FreeConsole`'s page, the console will get destroyed automatically when no process refers to it anymore.
So it works in our case, since our process created its own console.
Also if this is adopted, `showWindowAsyncProc` reference could be dropped
> Use FreeConsole instead of hiding

- examples/windowsize/main.go
- internal/uidriver/glfw/ui.go
When resizing with i3 (and possibly other WMs), the only way to now new framebuffer/window size is to get event from glfw.
This also calls `setWindowSizeInDIP` to update window size afterwards (instead of calling `context.Layout` directly)
Framebuffer size callbacks are used for handling window resize in glfw examples [like here](https://github.com/glfw/glfw/blob/master/examples/gears.c#L248)
I'm not 100% sure that this is the best solution, so any suggestions welcome.
@sedyh this might also fix #1620 - can you please check (there are still glitches, but maybe it's somewhat better)?
> Fix window float enable/disable (#1960)

- image.go
- internal/atlas/image.go
- internal/graphicsdriver/metal/graphics_darwin.go
- internal/graphicsdriver/opengl/defaultshader.go
Note that this applies only to the builtin shaders - interface for Kage stays
unchanged for compatibility.
Minor compatibility delta: when interpolating alpha values, previous code has
created nonsense values, such as, when interpolating from
fully-transparent-black (0,0,0,0) to opaque-white (1,1,1,1), something like
half-transparent-grey (0.25,0.25,0.25,0.5) where half-transparent-white
(0.5,0.5,0.5,0.5) is used by the new code.
I assume this is a strict improvement, however this may warrant some testing.
Possible later improvement could be moving the premultiplication from fragment
shader to CPU. Did not do this as it makes the code rather inconsistent of Kage
vs built-in shader usage.
Helps with https://github.com/hajimehoshi/ebiten/issues/1772, achieved 23fps->27fps and 36fps->48fps …
> Optimization: send premultiplied alpha from vertex to fragment shader.

- examples/blur/main.go
Also add a note that this is not how games should implement a blur if avoidable.
Comparison:
Before: https://rm.cloudns.org/img/uploaded/29c0418f25bf56b802f746d2f269e215.png
Note how Ebiten's blur has almost no vertical component.
After: https://rm.cloudns.org/img/uploaded/bd04828baf6c01fcf7301a6672a4c406.png
Note how after the change it looks basically like Krita's.
> Fix the blur filter example to be a real box blur.

- gameforui.go
- internal/ui/context.go
- run.go
Using FilterNearest rather than filterScreen or FilterLinear speeds up a
Dell E6500 from 23fps->36fps and 27fps->48fps.
Helps with https://github.com/hajimehoshi/ebiten/issues/1772.
> Provide ebiten.SetScreenFilterEnabled, a way to disable the default screen filter

- internal/gamepad/gamepad_linux.go
Fixes crash where Ebiten considers a keyboard a gamepad with way too many buttons.
For some reason, on one of my laptops, Ebiten tries to keyboard and touchpad devices as "gamepads" - but then when parsing its button data, it crashes. Apparently here, `EV_KEY` codes are returned with a code smaller than `_BTN_MISC` whenever pressing a key on the laptop.
https://github.com/hajimehoshi/ebiten/commit/b98568901086d92cf8a2565340a909cc04496822 attempted to fix this, but the subtraction was done as signed int data type, meaning it didn't actually detect underflow. My fix is doing the subtraction as uint16 just like in the following line where the same expression is used to access keyMap - an alternate fix would probably be adding an `e.code >= _BTN_MISC` check instead.
Helps with issue #2027.
> Fix uint16 underflow handling in gamepads.

- inpututil/inpututil.go
Fixes crash in inpututil when a gamepad with more than "allowed" buttons is
connected.
For some reason, on one of my laptops, Ebiten tries to keyboard and touchpad devices as "gamepads". The keyboard in particular shows up with `GamepadButtonNum(id) > GamepadButtonMax+1`.
https://github.com/hajimehoshi/ebiten/commit/5bb22d2bcf45fe026b99820c90b8bcc9e02fc19a attempted to fix this, but failed as other inpututil functions (e.g. `IsGamepadButtonJustPressed`) would still crash when a too-high button is passed, which happens in `examples/gamepad/main.go` due to it looping from `0` to `GamepadButtonNum(id)-1`.
An alternate fix could be already hiding extraneous buttons in the gamepad driver itself so that `GamepadButtonNum` can never return values greater than `GamepadButtonMax+1`; I decided not …
> inpututil: allow an arbitrary number of gamepad buttons.

- examples/stars/main.go
Minor adjustments because of:
- Function abs(int) is unused.
- Color fields are assigned without explicit names
- Color variable shadows the color package name
> Refactor example "stars"

- internal/graphicsdriver/opengl/graphics.go
- internal/graphicsdriver/opengl/graphics_notmobile.go
- internal/ui/graphics.go
- internal/ui/ui_android.go
- internal/ui/ui_cbackend.go
- internal/ui/ui_glfw_darwin.go
- internal/ui/ui_glfw_unix.go
- internal/ui/ui_glfw_windows.go
- internal/ui/ui_ios.go
- internal/ui/ui_js.go
This is a prepartion to return an error when a graphics driver, especially
DirectX, fails to initialize.
Updates #2142
> internal/graphicsdriver/opengl: replace Get with NewGraphics

- audio/vorbis/generate.go
- cmd/ebitenmobile/generate.go
- ebitenutil/internal/assets/assets.go
- examples/resources/generate.go
- examples/shader/generate.go
- internal/gamepaddb/gamepaddb.go
The tool is already referenced in `go.mod`, so it is trivial to just `go run` it - that way, `go generate` can use it without the user explicitly installing it first.
Tested: modifying `gobind.go` and running `go generate` now applies correctly to `gobind.src.go`.
Note that this means that `GOOS=windows go generate` no longer will work on Linux - if this is a problem, we could prepend the `go` command with `env GOOS= GOARCH=` every time. This same limitation also already exists for some of your `go run` commands in there, though, so I thought it's fine to keep it that way.
> Do not require installing file2byteslice to update go generate'd files.

- internal/gamepad/gamepad_linux.go
This change allows gamepad names up to 256 characters, which is usually
enough. Before, names were cut off after 7 characters, matching the string
"Unknown" that is used if querying the name fails.
> linux: Fix a typo that caused oddly cut off gamepad names.

- internal/gamepad/gamepad_linux.go
This appears to happen inside the Snap sandbox when accessing a non-gamepad /dev/input device.
> linux/gamepad: Do not fail on EPERM return values.

- internal/gamepaddb/gamepaddb.go
SDL interprets this as "map -1 to 1, map 0 to -1", so we should do the same.
This fix contains two parts:
- Fix the intended output range.
- Also fix the formula to map a range to a range.
The fix does not change behavior if a "-a" mapping isn't used, as in any other case max-min == 1 or max+min == 0.
Fixes #2334
> internal/gamepaddb: fix mapping support for e.g. `dpleft:-a0`.

- image.go
This reduces the struct size from 64 to 32 bytes.
> image: reorder fields as recommended by the fieldalignment utility

- audio/internal/convert/resampling.go
Addresses issue #2286 
Replaces the `cosTable` array with a slice that's filled in a getter that wraps a `sync.Once.Do`
> Add a lazy-load getter to ~/audio/internal/convert/resampling.go

- internal/gamepad/api_cf_darwin.go
- internal/gamepad/api_hid_darwin.go
- internal/graphicsdriver/metal/ca/ca_darwin.go
- internal/graphicsdriver/metal/mtl/example_darwin_test.go
- internal/graphicsdriver/metal/mtl/mtl_darwin.go
- internal/graphicsdriver/opengl/gl/procaddr_darwin.go
Updates #1162
bug 
dlopen requires either RTLD_LAZY or RTLD_NOW but there was neither.
> all: use RTLD_LAZY in dlopen for darwin

- internal/cocoa/api_cocoa_darwin.go
- internal/graphicsdriver/metal/mtl/mtl_darwin.go
Updates #1162 
feature
purego now supports using floats as arguments. We can remove these instances of NSInvocation that only existed to circumvent that feature.
> internal/cocoa & internal/graphicsdriver/mtl: remove usages of NSInvocations to directly call ID.Send

- internal/gamepad/api_cf_darwin.go
- internal/gamepad/api_hid_darwin.go
Updates #1162
bug
RegisterLibFunction is typesafe and now supports float arguments. This fixes the todo of not supporting seconds greater than 0 inside of `_CFRunLoopRunInMode`
> internal/gamepad: use RegisterLibFunc

- internal/graphicsdriver/opengl/program.go
- shader_test.go
Closes #2525
Closes https://github.com/divVerent/aaaaxy/issues/68
bug
After switching texture units using glActiveTexture, a different texture may be bound. For now, let's just force the active texture state variable to zero so the next glBindTexture call isn't skipped.
> opengl: Fix state tracking of glBindTexture / glActiveTexture interaction

- text/text.go
- vector/path.go
- vector/util.go
Signed-off-by: Pierre Curto <pierre.curto@gmail.com>
No issue required (as per the contributor guidelines) as this is basic typo fixes.
NA
Simple typos, unused function variables and unnecessary conversions.
> text,vector: fix typos and redundant casts

- blend.go
Closes #2560
Bug
Fixes BlendDestinationOut acting like BlendSourceOut.
> Fixed BlendDestinationOut behaviour #2560

- internal/goglfw/internal_windows.go
- internal/goglfw/wglcontext_windows.go
- internal/goglfw/win32init_windows.go
- internal/goglfw/win32monitor_windows.go
- internal/goglfw/win32platform_windows.go
- internal/goglfw/win32thread_windows.go
- internal/goglfw/win32window_windows.go
Updates #2546
feature
Many of the structs found in internal.h (internal_windows.go) contain defines such as GLFW_WIN32_WINDOW_STATE which gets replaced with a struct defined in win32platform_windows.go (win32_platform.h).
Originally, these structs where directly placed inside of internal_windows.go. However, to make it easier to add macOS and Linux these cannot be in this file.
This commit separates the windows specific structs into the respective windows file and updates the field to be named state.
> internal/goglfw: separate windows specific struct from common structs

- internal/goglfw/context_windows.go
Updates #2546
refactor
context_windows.go is used for all the platforms. However, it used syscall.Syscall which behaves differently on macOS and Windows as well as windows.BytePtrToString which isn't available on Linux or macOS.
This commit replaces syscall.Syscall with purego.SyscallN and windows.BytePtrToString with a copied version called bytePtrToString.
> internal/goglfw: use platform agnostic functions for context_windows.go

- internal/gamepad/gamepad.go
- internal/gamepad/gamepad_android.go
- internal/gamepad/gamepad_darwin.go
- internal/gamepad/gamepad_desktop_windows.go
- internal/gamepad/gamepad_ios.go
- internal/gamepad/gamepad_js.go
- internal/gamepad/gamepad_linux.go
- internal/gamepad/gamepad_nintendosdk.go
- internal/gamepad/gamepad_null.go
- internal/gamepad/gamepad_xbox_windows.go
- internal/gamepaddb/gamepaddb.go
Updates #2052
feature
Refactors native standard layout so standard axes and buttons can be implemented using any of axes, buttons or hats.
This is required to be able to implement a native standard layout mapping for Linux, as e.g. shoulder buttons can be backed either by an analog or digital input.
Precedes https://github.com/hajimehoshi/ebiten/pull/2587
> gamepad: enhanced native standard layout support

- internal/gamepad/api_linux.go
- internal/gamepad/gamepad_linux.go
Closes #2052
feature
Implements native standard layout for Linux gamepads by using the kernel-provided button IDs, thereby expanding support to gamepads not listed in `gamecontrollerdb.txt`.
Requires https://github.com/hajimehoshi/ebiten/pull/2588
Linux's docs: https://www.kernel.org/doc/Documentation/input/gamepad.txt
SDL2's source: https://fossies.org/linux/SDL2/src/joystick/linux/SDL_sysjoystick.c#l_1740
Note that I am NOT 100% convinced about the X/Y swap between Xbox and PlayStation controllers - the Xbox compatible pad I have however does have `BTN_NORTH` and `BTN_WEST` swapped (and thus `BTN_X` and `BTN_Y` assigned right), which confirms SDL's logic and opposes the kernel docs.
Tested with this gamepad: "20d6:2802 BDA Xbox ONE Core controller", label says "PowerA Model 1508491-02" …
> gamepad: native standard layout for Linux

- internal/packing/packing.go
Closes #2628
bug
By removing redundant work done in canAlloc and just calling alloc right away, this removes 35% contribution to AAAAXY loading CPU time on the profile on https://user-images.githubusercontent.com/251568/230496805-c5e32c19-9258-49c8-800b-a3f0bc3b072d.svg, or - as measured via stopwatch - brings loading time on Moto G7 Play from 17.22s to 14.94s after already applying https://github.com/hajimehoshi/ebiten/pull/2627.
This should be safe as there is no case in which alloc succeeds and the allocated region isn't used; also, there is no case in which alloc mutates the tree when it doesn't actually succeed (comment added in one place to justify this).
> packing: remove redundant canAlloc checking and alloc allocating.

- internal/restorable/export_test.go
- internal/restorable/image.go
- internal/restorable/rect_test.go
Closes #2626
bug
This is achieved by replacing the function by one that only adds a single new region, and only considers duplicates between the previously existing region and the one newly added one, thereby removing previously redundant checking of each previously existing region against each other.
This speeds up AAAAXY loading on a Moto G7 Play from 52.27 seconds to 8.15 seconds.
Same profiling info as for https://github.com/hajimehoshi/ebiten/pull/2627 applies here too - the new code doesn't appear in the profile graph at all.
> removeDuplicatedRegions: change from O((n+m)^2) to O(n*m + m^2).

- internal/goglfw/api_windows.go
Negative values should not disappear. For example, if _HIWORD returns 63000, then _GET_Y_LPARAM should return -2536, but now it returns 63000. This fixes that.
Here's how it's defined in windowsx.h:
`#define GET_X_LPARAM(lp)                        ((int)(short)LOWORD(lp))`
`#define GET_Y_LPARAM(lp)                        ((int)(short)HIWORD(lp))`
> Fix _GET_X_LPARAM and _GET_Y_LPARAM from api_windows.go

- internal/ui/image.go
Closes #2679 
bug
Fixes coordinate transformation math on dstRegion.
Previous code had x1 and y1 shifted by exactly (i.region.X, i.region.Y), which allowed it to exceed the width and height of the destination image. iOS MTLDebugRenderCommandEncoder detects this issue and crashes.
No known test case for OpenGL or similar, as the rectangle is always strictly larger or equal to the correct rectangle.
It is POSSIBLE, but not reproduced, this this can in OpenGL cause DrawTriangles to draw on a different image than the destination image if they share an atlas. However, as this depends a lot on how the atlas is built, I am not sure if it can actually be triggered reliably, or even at all.
> Fix antialias region size

- mobile/ebitenmobileview/input.go
- mobile/ebitenmobileview/input_android.go
- mobile/ebitenmobileview/input_ios.go
This prevents duplicate input characters due to concurrent touch events.
Closes #2682
bug
`updateInput` currently receives `runes` in a global variable as a hidden parameter. Some calls do not clear it though, but leave the previous value in it - in particular calls on behalf of touch or key release events.
> Make runes a parameter.

- mobile/ebitenmobileview/input_android.go
Closes #2684
bug
It makes it possible to still receives characters from a key that Ebitengine does not know about. This can be helpful with international text entry.
> Android: support keypress runes even for unmapped keys

- examples/gamepad/main.go
Start iterating at zero instead of gamepad id (which is usually 0).
bug
fixes small bug ;)
> Correct iteration start button in gamepad example

- internal/ui/ui_glfw.go
#2725
Issue #2725 is written as a feature request but it looks like that request was only made because the feature would mitigate a bug it describes (white flash of window background before content is shown on Windows). This PR removes the need for the feature by resolving that bug.
The PR delays window.Show until after the first buffer swap, which was already the way it was done under macOS. This avoids the window appearing before its contents have been initialized by the user.
> internal/ui: show window after first draw on glfw

- internal/graphicscommand/commandqueue.go
Follow up on discussion #2882, found that uniform variables are hard-coded to four images.
Addresses a feature request.
These changes allow increasing `ShaderImageCount` without breaking the image display.
Simply made the uniform processing dynamic based on `ShaderImageCount`.
It doesn't actually increase the image count, as the value used there likely needs to depend on the system the code is running on. Would be happy to discuss that and make the necessary changes in a future PR.
> feat(kage): support variable shader image count

- image.go
- internal/atlas/image.go
- internal/atlas/image_test.go
- internal/atlas/shader_test.go
- internal/buffered/image.go
- internal/buffered/image_test.go
- internal/graphics/shader.go
- internal/graphics/vertex.go
- internal/graphicscommand/command.go
- internal/graphicscommand/commandqueue.go
- internal/graphicscommand/image.go
- internal/graphicscommand/image_test.go
- internal/graphicsdriver/directx/graphics11_windows.go
- internal/graphicsdriver/directx/graphics12_windows.go
- internal/graphicsdriver/directx/pipeline12_windows.go
- internal/graphicsdriver/directx/shader11_windows.go
- internal/graphicsdriver/graphics.go
- internal/graphicsdriver/metal/graphics_darwin.go
- internal/graphicsdriver/opengl/graphics.go
- internal/graphicsdriver/opengl/program.go
- internal/graphicsdriver/playstation5/graphics_playstation5.go
- internal/mipmap/mipmap.go
- internal/ui/image.go
This just specifies that the constant refers to the number of source images passed to a shader (as discussed on discord).
This makes a distinction with the number of dst images, that could potentially be more than 1 in the future
> Renamed shader image count to specify src

- image.go
Reduces allocations and GC overhead for programs that call `ebiten.Image.DrawTriangles` hundreds of times per rendered frame.
> Update image.DrawTriangles to re-use indices

- internal/graphics/vertex.go
- internal/graphicscommand/command.go
- internal/graphicscommand/commandqueue.go
- internal/graphicscommand/image.go
- internal/graphicsdriver/directx/graphics11_windows.go
- internal/graphicsdriver/directx/graphics12_windows.go
- internal/graphicsdriver/graphics.go
- internal/graphicsdriver/metal/graphics_darwin.go
- internal/graphicsdriver/opengl/graphics.go
- internal/graphicsdriver/playstation5/graphics_playstation5.go
This adds a `ShaderDstImageCount` to pair with `ShaderSrcImageCount` for consistency.
This also specifies an array of that size as destination images to prepare for a potential future with multiple render targets.
> Open up for more destinations images

- internal/ui/ui_js.go
[internal/ui: crash by dropping an HTML element onto the canvas](https://github.com/hajimehoshi/ebiten/issues/3043)
The application crashes when an HTML element is dropped onto the canvas.
This pull request addresses the crash by implementing the following:
- Loops through all dropped items
- Only handles items with the "file" kind
- Ignores other types of dropped elements, preventing the crash
- Convert `DroppedFiles` to an array to handle multiple file drops
- Implement handling for all types of dropped items under the switch case
> internal/ui: crash by dropping an HTML element onto the canvas

- image.go
This is a performance patch to remove extra variable copying when looping through vertices in `Image.DrawTriangles()` and `Image.DrawTrianglesShader()`.
Performance
This PR replaces `for i, v := range vertices` with `for i := range vertices` and indexes the `vertices` slice to allow the functions to behave the same while avoiding unnecessarily allocating an extra `ebiten.Vertex` in each loop iteration.
This PR should resolve issue #3103.
> ebiten: don't create a Vertex copy in DrawTriangles() / DrawTrianglesShader()

- internal/graphicsdriver/opengl/gl/default_js.go
Unsure if this is connected with any existing issues.
bug
This is just what appears to be a typo in the WebGL driver that is deleting the mapping between a uint32 ID and a JavaScript value  for vertexArrays from the value store for the textures instead. This seems like it would potentially cause a crash if the numbers aligned.
I'm not sure exactly how to test this! I don't believe anything would happen to the vertexArrays lookups other than the map taking up a small amount more space, but if a live texture has the same ID as a deleted vertex array, I believe the map lookup would panic and crash.
> Fixes DeleteVertexArrays removing entry from textures in webgl driver

- .gitignore
- cmd/ebitenmobile/gomobile.go
This PR solves:
#3128
The reason this happens is that runtime.Version() returns this value when loopvar variable is set:
"go1.23.2 X:loopvar"
> Fix gomobile toolchain bug

- internal/cocoa/api_cocoa_darwin.go
- internal/graphicsdriver/metal/ca/ca_darwin.go
- internal/graphicsdriver/metal/graphics_darwin.go
- internal/graphicsdriver/metal/mtl/mtl_darwin.go
- internal/ui/ui_darwin.go
Cache the result of objc.RegisterName at program startup. Use NSInvocation less to avoid multiple C calls
n/a
performance
Lowers memory usage
> internal/cocoa, internal/graphicsdriver/metal/*: minimize allocations

- image.go
Since it's not allowed to have differently-sized images for DrawTrianglesShaderOptions in pixels mode, the comment should be updated.
None
It's just a comment update.
Makes the engine's feature more apparent, instead of stating that doing something is impossible while it is possible.
> clarify the same images size rule for DrawTrianglesShaderOptions

- window.go
Added a period to the function description, making it easier to read in the IDE hover tooptip.
Trivial fix, no issue
Clarity of code comments
On hover tooltip, the added period makes it more clear
`WindowSize returns the original window size If you need the fullscreen dimensions, see Monitor().Size() instead.`
`WindowSize returns the original window size.  If you need the fullscreen dimensions, see Monitor().Size() instead.`
> Fixed typo in comment

- audio/internal/convert/stereoi16.go
- audio/internal/convert/stereoi16_test.go
- audio/vorbis/vorbis.go
- audio/wav/decode.go
Updates #2215
feature
This changes StereoI16 to accept 24bit integer stream as a preparation for the 24bit WAV format.
> audio/internal/convert: make StereoI16 accept a 24bit stream

- internal/ui/ui_glfw.go
Workaround for #3241.
While this fixes the issue, I am not sure this should be the definitive fix.
A better alternative could be to turn off rendering entirely when all monitors are offline?
With that being said, this workaround prevents a crash and the engine continues working after one monitor goes back online.
Resolves a panic
Fallback to init monitor data when primary monitor goes offline
> fallback to init monitor if primary is off

- image.go
The existing comment for the `Set` method in `image.go` notes that calls on disposed images do nothing. This PR adds a similar clarification for out-of-bounds coordinates.
> Clarify Image Set does nothing for out-of-bounds coordinates

- internal/shaderir/reachable_test.go
In the Go 1.21 standard library, a new function has been introduced that enhances code conciseness and readability. It can be find  [here](https://pkg.go.dev/slices@go1.21.1#Equal).
refactor
> refactor: use slices.Equal to simplify code

- examples/vector/main.go
Delete unused `x` and `y` parameters from `drawEbitenText` function.
> examples vector remove unused params

- internal/shaderir/program.go
Replaces strings.IndexRune checks with strings.ContainsRune in IsValidSwizzling for improved readability and idiomatic Go usage.
> all: Refactor swizzling validation to use ContainsRune

- examples/masking/main.go
- image_test.go
Updated code to use image.Point{} instead of image.ZP and image.Rectangle{} instead of image.ZR, as the former are deprecated. This improves code clarity and future compatibility.
> all: Replace deprecated image.ZP and image.ZR usages

- examples/contextlost/main.go
- examples/keyboard/keyboard/gen.go
- examples/mandelbrot/main.go
- examples/masking/main.go
- examples/moire/main.go
- examples/noise/main.go
Replaces traditional for-loop constructs with 'for range' syntax in several example files for improved readability and idiomatic Go style. Affects contextlost, keyboard, mandelbrot, masking, moire, and noise examples.
> examples: Refactor loops to use range in example files

- internal/graphicsdriver/metal/ca/ca_darwin.go
Refactored panic calls to use fmt.Errorf() directly instead of wrapping errors.New(fmt.Sprintf()), simplifying error creation in SetPixelFormat and SetMaximumDrawableCount.
> all: Replace errors.New(fmt.Sprintf()) with fmt.Sptrinf()
